### ISSUE TITLE
End foliage will generate underwater

### ISSUE THREAD

**Issue by OpenBagTwo** [OpenBagTwo/LighterEnd#31]
## Summary

Megalakes consistently end up having umbrella ferns and other `END_MOSS_VEGETATION` show up in shallow water.

![Creeping moss surrounded by water](https://github.com/user-attachments/assets/6d717699-5d1f-4af9-9d89-596d9c337177)

## Environment and Version

- Minecraft version: 1.21.6-pre3
- LighterEnd version: v0.1.0-pre2
- Fabric Loader / API version: 1.26.0-1.21.6
- Any other relevant mods or datapacks you have installed:
- The contents of your `lighterend.yaml` configuration file
  (inside your `.minecraft` / instance folder, under `config`):

```yaml
generate_biomes: true
play_biome_music: true
end_gravity: 0.3
music_discs_found_in_end_cities: true
bonemealing_underwater_in_the_end_produces_end_vegetation: true
```

## Steps to Reproduce
1. Create a world
2. Find a megalake (might take you a minute)

## Workaround

Break the foliage? Ignore it?

## Severity

Annoying

## Desired Outcome

Fix

## Urgency

Slating for Beta 2
