### ISSUE TITLE
End foliage will replace other blocks during generation

### ISSUE THREAD

**Issue by lbyzalov** [OpenBagTwo/LighterEnd#38]
## Summary

Umbrella and Creeping ferns can replace other solid blocks during world generation

[Issue affecting End City](https://i.imgur.com/ZNg3eB6.png)
[Issue affecting Lumecorn plant](https://i.imgur.com/qo5rwk8.png)

## Environment and Version

- Minecraft version: 1.21.5 (Fabric)
- LighterEnd version: 0.1.0-pre4
- Launcher: Minecraft Launcher
- Fabric API version:1.126.0
- Any other relevant mods or datapacks you have installed: None
- LighterEnd config: default

```yaml
generate_biomes: true
play_biome_music: true
end_gravity: 0.3
end_plants_only_grow_in_the_end: true
music_discs_found_in_end_cities: true
bonemealing_underwater_in_the_end_produces_end_vegetation: true
```

## Steps to Reproduce

1. Create a new world with these settings
2. Go to the outer end
3. Look around glowing grassland biomes, paying attention to lumecorn plants and end cities

## Relevant Log

<details><summary>Click to reveal</summary>

```

```

</details>

## Workaround

None

## Severity

- Annoying

## Desired Outcome

- Fix
