### ISSUE TITLE
Each half of a door from this mod drops a full door when broken

### ISSUE THREAD

**Issue by lbyzalov** [OpenBagTwo/LighterEnd#39]
## Summary

When breaking a door added by this mod, both halves of the door drop a door item, instantly duplicating the door.

## Environment and Version

- Minecraft version: 1.21.5 (Fabric)
- LighterEnd version: 0.1.0-pre4
- Launcher: Minecraft Launcher
- Fabric API version:1.126.0
- Any other relevant mods or datapacks you have installed: None
- LighterEnd config: default

```yaml
generate_biomes: true
play_biome_music: true
end_gravity: 0.3
end_plants_only_grow_in_the_end: true
music_discs_found_in_end_cities: true
bonemealing_underwater_in_the_end_produces_end_vegetation: true
```

## Steps to Reproduce

1. Obtain a door added by this mod
2. Break it in survival mode

## Severity

- Annoying

## Desired Outcome

- Fix
