### ISSUE TITLE
Some mobs have lacking or incorrect subtitle strings

### ISSUE THREAD

**Issue by lbyzalov** [OpenBagTwo/LighterEnd#40]
## Summary

Mobs added by this mod have lacking or incorrect subtitle strings.

Dragonflies have no subtitle strings

End Fish reuse Tropical Fish subtitle strings

Cubozoa reuse Pufferfish and Salmon subtitle strings

## Environment and Version

- Minecraft version: 1.21.5 (Fabric)
- LighterEnd version: 0.1.0-pre4
- Launcher: Minecraft Launcher
- Fabric API version:1.126.0
- Any other relevant mods or datapacks you have installed: None
- LighterEnd config: default

```yaml
generate_biomes: true
play_biome_music: true
end_gravity: 0.3
end_plants_only_grow_in_the_end: true
music_discs_found_in_end_cities: true
bonemealing_underwater_in_the_end_produces_end_vegetation: true
```

## Steps to Reproduce

1. Enable subtitles
2. Use a spawn egg to spawn the listed mobs

## Severity

- Trivial

## Desired Outcome

- Implement strings

## Urgency

- Not urgent
