### ISSUE TITLE
Tenania Sapling has incorrect item model

### ISSUE THREAD

**Issue by lbyzalov** [OpenBagTwo/LighterEnd#41]
## Summary

The Tenanea sapling uses its block model as an item model instead of having a separate item model (as with vanilla saplings). In addition, due to this, it is shaded too dark in the inventory.

## Environment and Version

- Minecraft version: 1.21.5 (Fabric)
- LighterEnd version: 0.1.0-pre4
- Launcher: Minecraft Launcher
- Fabric API version:1.126.0
- Any other relevant mods or datapacks you have installed: None
- LighterEnd config: default

```yaml
generate_biomes: true
play_biome_music: true
end_gravity: 0.3
end_plants_only_grow_in_the_end: true
music_discs_found_in_end_cities: true
bonemealing_underwater_in_the_end_produces_end_vegetation: true
```

## Steps to Reproduce

1. Obtain Tenanea Sapling item
2. Drop it on the ground

## Severity

- Trivial

## Desired Outcome

- Implement correct item model

## Urgency

- Not urgent
