### ISSUE TITLE
End Moss is not carved out by lakes and generates in sheets within water

### ISSUE THREAD

**Issue by lbyzalov** [OpenBagTwo/LighterEnd#42]
## Summary

Within lakes of water, the lake carver removes end stone but not end moss. This causes sheets of end moss to appear in lakes, with water above and below them.

## Environment and Version

- Minecraft version: 1.21.5 (Fabric)
- LighterEnd version: 0.1.0-pre4
- Launcher: Minecraft Launcher
- Fabric API version:1.126.0
- Any other relevant mods or datapacks you have installed: None
- LighterEnd config: default

```yaml
generate_biomes: true
play_biome_music: true
end_gravity: 0.3
end_plants_only_grow_in_the_end: true
music_discs_found_in_end_cities: true
bonemealing_underwater_in_the_end_produces_end_vegetation: true
```

## Steps to Reproduce

1. Generate world
2. Locate and travel to Megalake biome
3. Use spectator mode to observe moss generation

## Severity

- Annoying

## Desired Outcome

- Fix
