### ISSUE TITLE
Umbrella Membranes incorrectly unlock unrelated recipe

### ISSUE THREAD

**Issue by lbyzalov** [OpenBagTwo/LighterEnd#43]
## Summary
When obtaining an Umbrella Membrane block, the player immediately unlocks the recipe for crafting slime blocks into slime balls.

## Environment and Version

- Minecraft version: 1.21.5 (Fabric)
- LighterEnd version: 0.1.0-pre4
- Launcher: Minecraft Launcher
- Fabric API version:1.126.0
- Any other relevant mods or datapacks you have installed: None
- LighterEnd config: default

```yaml
generate_biomes: true
play_biome_music: true
end_gravity: 0.3
end_plants_only_grow_in_the_end: true
music_discs_found_in_end_cities: true
bonemealing_underwater_in_the_end_produces_end_vegetation: true
```

## Steps to Reproduce

1. Generate new world
2. Obtain Umbrella Membrane by any means without first obtaining a slime block

## Severity

- Trivial

## Desired Outcome

- Fix
