### ISSUE TITLE
End Moss is untinted when held by endermen

### ISSUE THREAD

**Issue by lbyzalov** [OpenBagTwo/LighterEnd#48]
## Summary

When an enderman holds an end moss block, that block is untinted.

## Environment and Version

- Minecraft version: 1.21.6
- LighterEnd version: v0.1.1
- Launcher: Minecraft Launcher
- Fabric API version: 0.127.1
- Any other relevant mods or datapacks you have installed: N/A
- LighterEnd config: default

```yaml
generate_biomes: true
play_biome_music: true
end_gravity: 0.3
end_plants_only_grow_in_the_end: true
music_discs_found_in_end_cities: true
bonemealing_underwater_in_the_end_produces_end_vegetation: true
```

## Steps to Reproduce

Spawn in an enderman that is holding an end moss block, or find one naturally spawning

## Relevant Log

<details><summary>Click to reveal</summary>

```

```

</details>

## Severity

- Trivial

## Desired Outcome

- fix
